startTime = datestr(now);
save([path,'/','timeMetafile.mat'],'orcaExp', 'AmExp', ...
              'binning', 'AmCrop', 'OrcaCrop', 'AmGain', 'path', 'startTime', ...
              'TimeX', 'TimeY', 'TimeX', 'TimeInterval', 'LEDPower', 'Zdepth', 'Zinterval');
          
% clear('calExp','calAvg','xCount','yCount','zCount','xStep','yStep','zStep', ...
%               'binning','hPos','vPos','imageSize','extPower','startTime');

