startTime = datestr(now);
save([path,'/','supMetafile.mat'],'orcaExp', 'Support', 'Surface', 'AmExp', ...
              'binning', 'path', 'startTime', ...
              'LEDPower', 'FrameAve', 'AmCrop', 'OrcaCrop', 'AmGain');
          
% clear('calExp','calAvg','xCount','yCount','zCount','xStep','yStep','zStep', ...
%               'binning','hPos','vPos','imageSize','extPower','startTime');

